// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PGMExpectCpp
NumericVector PGMExpectCpp(IntegerVector varDimensions, List facPotentials1, List facPotentials2, List facNeighbors);
RcppExport SEXP PGMscore_PGMExpectCpp(SEXP varDimensionsSEXP, SEXP facPotentials1SEXP, SEXP facPotentials2SEXP, SEXP facNeighborsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type varDimensions(varDimensionsSEXP );
        Rcpp::traits::input_parameter< List >::type facPotentials1(facPotentials1SEXP );
        Rcpp::traits::input_parameter< List >::type facPotentials2(facPotentials2SEXP );
        Rcpp::traits::input_parameter< List >::type facNeighbors(facNeighborsSEXP );
        NumericVector __result = PGMExpectCpp(varDimensions, facPotentials1, facPotentials2, facNeighbors);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
