# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkAcyclic <- function(rFacNbs) {
    .Call('dgRaph_checkAcyclic', PACKAGE = 'dgRaph', rFacNbs)
}

cumulant <- function(t, p, s) {
    .Call('dgRaph_cumulant', PACKAGE = 'dgRaph', t, p, s)
}

cumulantD1 <- function(t, p, s) {
    .Call('dgRaph_cumulantD1', PACKAGE = 'dgRaph', t, p, s)
}

cumulantD2 <- function(t, p, s) {
    .Call('dgRaph_cumulantD2', PACKAGE = 'dgRaph', t, p, s)
}

