# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkAcyclic <- function(rFacNbs) {
    .Call('dgRaph_checkAcyclic', PACKAGE = 'dgRaph', rFacNbs)
}

evalDFG <- function(x) {
    .Call('dgRaph_evalDFG', PACKAGE = 'dgRaph', x)
}

mgfDFG <- function(varDimensions, facPotentials, facNeighbors) {
    .Call('dgRaph_mgfDFG', PACKAGE = 'dgRaph', varDimensions, facPotentials, facNeighbors)
}

PGMExpectCpp <- function(varDimensions, facPotentials1, facPotentials2, facNeighbors) {
    .Call('dgRaph_PGMExpectCpp', PACKAGE = 'dgRaph', varDimensions, facPotentials1, facPotentials2, facNeighbors)
}

sampleISCpp <- function(N, alpha, varDimensions, facPotentialsNull, facNeighbors, facPotentialsFg) {
    .Call('dgRaph_sampleISCpp', PACKAGE = 'dgRaph', N, alpha, varDimensions, facPotentialsNull, facNeighbors, facPotentialsFg)
}

